### ISSUE TITLE
Improvement/Refac: Rename EventManager to Logger or something similar

### ISSUE THREAD

**Issue by clemensjur** [teamAF-FHCampusWien/richAF#8]
We should think about renaming the EventManager class to Logger or something similar, if the only function of the class is to write to a logfile.

If it is planned to implement an EventManger that handles certain events and acts on them we should think about separating event handling/managing and logging anyways.

**Comment by TheBloodyAmateur** [comment]
The Term "EventManager" was meant as a class that manages the single entries of a log, aka an event. If the other team members agree and think another name might be more suitable I can obviously change it. Let me know what you think!
