### ISSUE TITLE
Improvement: Allow logErrorMessage method to receive an Exception object as input 

### ISSUE THREAD

**Issue by clemensjur** [teamAF-FHCampusWien/richAF#9]
We should think about allowing the logErrorMessage method to receive an Exception object as input so we don't have to write `logErrorMessage(exception.getMessage())` but rather `logErrorMessage(exception)`

**This is not a needed improvement, but could improve usability of the EventManager**

**Comment by TheBloodyAmateur** [comment]
Fair point, will work on it.

**Comment by TheBloodyAmateur** [comment]
Is done. Read my pull request for further information.
